language: ruby

rvm:
- 2.2.2

install: gem install i18n jekyll jekyll-paginate jemoji html-proofer minitest i18n
script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --empty-alt-ignore

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
