
# Site settings 

# NB! Set your site's url, otherwise stuff will break :)

url: "http://vgarcia.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-71882862-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Victor Garcia"
title: "{ Victor Garcia }"
description: "Blog and website of Victor Garcia"
keywords: "Victor Garcia"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/Perseiid.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Software Developer | Agilist | Humanist"

me-img: "/img/hawaii.jpeg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 50

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: portenez

syntax-highlight: True

############
# Timeline #
############

#events:
#  - image: "/img/timeline/spidertocat.png"
#    date: "September 2013 - Today"
#    description: "Saving the neighborhood!"
#  - image: "/img/timeline/baracktocat.jpg"
#    date: "September 2007 - August 2013"
#    description: "Started coding"

# First image of the Timeline

#timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "info@vgarcia.me"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/portenez"
  - title: "github"
    url: "https://github.com/portenez"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/vhgarciavalencia"
  - title: "youtube"
    url: https://www.youtube.com/channel/UCrDGC0ec_9m0yxOBVTu5NdQ

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
#  Timeline: 'timeline'
  Contact: 'contact'
  CV: 'cv'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
