# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://le4ker.github.io"
baseurl: "/personal-jekyll-theme"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "John Smith"
title: "{ John Smith }"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "Whereâ€™s your will to be weird?"
me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "your@email.here"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "/img/author.png"
author_blurb:
  "'Github''s Octocat was designed by Simon Oxley, alongside the white bird Twitter
  used (before they received a proper logo) as part of a usual routine of cranking
  out images for iStock. GitHub saw it, and wanted it, presumably under the notion
  that it can represent how complex code combines to create peculiar things, much
  like the octopuss... except the CEO of GitHub called it an octocat, and it has
  been the octocat since then."

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/le4ker/personal-jekyll-theme"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com"
  - icon: "x-twitter"
    url: "https://twitter.com/"
  - icon: "rss"
    url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
