
# Site settings
gems: [jekyll-paginate]

url: "https://njaremko.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

google-tracking-id: "UA-69345024-1"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Nathan Jaremko"
lang: "en"
title: "{ Nathan Jaremko }"
favicon: "/img/favicon.ico"
description: "The blog and website of Nathan Jaremko. I'm a software engineering co-op student at the University of Toronto. Here you'll find the projects I'm working on, jobs I've done, and some info about me."
keywords: "nathan, jaremko, personal, github, developer, engineer, software"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/me.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	1		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Martin Golding"
  - text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates"
  - text: "If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra"
  - text: "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program. - Linus Torvalds"
  - text: "To iterate is human, to recurse divine. - L. Peter Deutsch"
  - text: "$ sudo make a_sandwich"
  - text: "Garbage to ten decimal places is still garbage."
  - text: "If you don't want to be replaced by a computer, don't act like one."
  - text: "Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing."
  - text: "Beware of bugs in the above code; I have only proved it correct, not tried it. - Donald E. Knuth."

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "njaremko"

###############
# Life Events #
###############

events:
  - image: "/img/career/pcc.png"
    date: "September 2015 - Today"
    description: "Quality Analyst @ PointClickCare"
  - image: "/img/career/baracktocat.jpg"
    date: "June 2013 - August 2013"
    description: "Game Development Intern @ Sault Ste. Marie Innovation Centre"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "njaremko@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/njaremko"
  - title: "linkedin"
    url: "https://ca.linkedin.com/in/njaremko"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/4547413/nathan-jaremko"
  - title: "github"
    url: "https://github.com/njaremko"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.md", "vendor"]
