
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://lxynox.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "lxynox"
title: "‚ñ≥ lxynox ‚ñº"
description: "A panda rambles on the web, speaks a little bit JavaScript for fun #üë∂dev_for_life"
keywords: "jekyll, blog, personal site"
favicon: "/img/profile.ico"

################
# Header layout #
################

black-favicon: "/img/profile.ico"

background-img: "../img/bg_vimrc.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add  HTML Tags in the Text
  - text: "One of the greatest pleasures in life is doing what other people say you can't. - Sindre Sorhus"
  - text: "Those who are crazy enough to think they can change the world usually do. - Steve Jobs"
  - text: "The dream of yesterday, is the hope of today, and the reality of tomorrow. - Robert H. Goddard"

me-img: "/img/profile.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/react_logo.png"
    date: "June, 2016 - Today"
    description: "Idle. Everything around React.js is so cool‚òú(‚åí‚ñΩ‚åí)‚òû"
  - image: "/img/timeline/CA_logo.jpg"
    date: "Jan, 2016 - May, 2016"
    description: "Internship. Wait, ECMAScript is JavaScript‚ÅâÔ∏è"
  - image: "/img/timeline/WPI_logo.png"
    date: "Sep 2014 - May, 2016"
    description: "Master. Wow, land in the US üá∫üá∏"
  - image: "/img/timeline/BIT_logo.png"
    date: "Sep 2010 - May, 2014" 
    description: "Undergrad. Seriously, we were all young „ÉΩ(¬¥‚ñΩ`)/"

# First image of the Timeline

timeline-img: "/img/timeline/default.gif"

###########
# Contact #
###########

email: "lxynox@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "lxynox is a pure lazy person, he doesn't like to leave any descriptions about himself."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/lxynox"
  - title: "twitter"
    url: "https://twitter.com/lxynox"
  - title: "github"
    url: "https://github.com/lxynox"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
