# Site settings

author: "John Smith"
url: "http://panossakkos.github.io/personal-jekyll-theme/"
lang: "en"
title: "{ John Smith }"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "img/favicon.ico"
black-favicon: "img/black-lab-glass.ico"
google-tracking-id: "<YOUR GOOGLE TRACKING ID>"
disqus-shortname: "<YOUR DISQUS USERNAME>"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Enable minification SASS
sass:
  style: compressed

background-img: "http://panossakkos.github.io/personal-jekyll-theme/img/intro-bg.jpg"

# About variables

me-img: "img/jetpacktocat.png"

# Blog variables

paginate: 5

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  - image: "img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "img/career/default.png"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
# Add a url pointing to your profile for earch social network.

social:
  - title: "github"
    url: "https://github.com/"
  - title: "linkedin"
    url: "http://no.linkedin.com/"
  - title: "youtube"
    url: "http://youtube.com/"
  - title: "rss"
    url: "/feed.xml"

404-img: "img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
